[package]
name = "llm-chain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.67"
dynfmt = { version = "0.1.5", features = ["curly"], default-features = false }
futures = "0.3.27"
